#!/usr/bin/env bash
# Aegis — Linux/macOS bootstrap + UI launcher
# Installs (best-effort): Python venv deps, Node deps, OpenMPI, then starts API + web UI.
# Windows users: use setup_and_run.cmd instead.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

info() { printf '\n=== %s ===\n' "$*"; }
ok() { printf '[OK] %s\n' "$*"; }
warn() { printf '[WARN] %s\n' "$*" >&2; }

ensure_mpi() {
  info "MPI (OpenMPI / system mpiexec)"
  if [[ -n "${AEGIS_MPIEXEC:-}" && -x "${AEGIS_MPIEXEC}" ]]; then
    ok "AEGIS_MPIEXEC=${AEGIS_MPIEXEC}"
    return 0
  fi
  if command -v mpiexec >/dev/null 2>&1; then
    export AEGIS_MPIEXEC="$(command -v mpiexec)"
    ok "MPI launcher already present: ${AEGIS_MPIEXEC}"
    return 0
  fi
  if command -v mpirun >/dev/null 2>&1; then
    export AEGIS_MPIEXEC="$(command -v mpirun)"
    ok "MPI launcher already present: ${AEGIS_MPIEXEC}"
    return 0
  fi
  if [[ "${AEGIS_INSTALL_MPI:-1}" == "0" ]]; then
    warn "Skipping MPI install (AEGIS_INSTALL_MPI=0)."
    return 0
  fi
  if command -v apt-get >/dev/null 2>&1; then
    warn "Installing OpenMPI via apt (may need sudo)…"
    sudo apt-get update -y
    sudo apt-get install -y openmpi-bin libopenmpi-dev || warn "apt OpenMPI install failed"
  elif command -v dnf >/dev/null 2>&1; then
    warn "Installing OpenMPI via dnf (may need sudo)…"
    sudo dnf install -y openmpi openmpi-devel || warn "dnf OpenMPI install failed"
  elif command -v yum >/dev/null 2>&1; then
    warn "Installing OpenMPI via yum (may need sudo)…"
    sudo yum install -y openmpi openmpi-devel || warn "yum OpenMPI install failed"
  elif command -v brew >/dev/null 2>&1; then
    warn "Installing OpenMPI via Homebrew…"
    brew install open-mpi || warn "brew OpenMPI install failed"
  else
    warn "No known package manager for OpenMPI. Install openmpi-bin / open-mpi manually."
  fi
  hash -r 2>/dev/null || true
  if command -v mpiexec >/dev/null 2>&1; then
    export AEGIS_MPIEXEC="$(command -v mpiexec)"
    ok "MPI launcher installed: ${AEGIS_MPIEXEC}"
  elif command -v mpirun >/dev/null 2>&1; then
    export AEGIS_MPIEXEC="$(command -v mpirun)"
    ok "MPI launcher installed: ${AEGIS_MPIEXEC}"
  else
    warn "mpiexec/mpirun still missing. Parallel LAMMPS (mpi_procs>1) will not work until MPI is installed."
  fi
}

ensure_python() {
  info "Python venv + API deps"
  if [[ ! -d .venv ]]; then
    python3 -m venv .venv
  fi
  # shellcheck disable=SC1091
  source .venv/bin/activate
  python -m pip install -U pip
  python -m pip install -r apps/api/requirements.txt
  ok "API Python deps ready"
}

ensure_node() {
  info "Web UI deps"
  if ! command -v npm >/dev/null 2>&1; then
    warn "npm not found — install Node.js LTS, then re-run."
    return 1
  fi
  (cd apps/web && npm install)
  ok "Web dependencies ready"
}

write_env() {
  local envf="${ROOT}/tools/aegis_env.sh"
  mkdir -p "${ROOT}/tools"
  cat >"${envf}" <<EOF
# Auto-generated by setup_and_run.sh — local only
export AEGIS_LAMMPS_BIN="\${AEGIS_LAMMPS_BIN:-$(command -v lmp 2>/dev/null || true)}"
export AEGIS_MPIEXEC="\${AEGIS_MPIEXEC:-${AEGIS_MPIEXEC:-}}"
export AEGIS_KART_ROOT="\${AEGIS_KART_ROOT:-}"
export AEGIS_KART_BIN="\${AEGIS_KART_BIN:-}"
EOF
  ok "Wrote ${envf}"
}

start_aegis() {
  info "Launching Aegis"
  # shellcheck disable=SC1091
  source .venv/bin/activate
  if [[ -f tools/aegis_env.sh ]]; then
    # shellcheck disable=SC1091
    source tools/aegis_env.sh
  fi
  export PYTHONPATH="${ROOT}/packages/schema:${ROOT}/engines:${PYTHONPATH:-}"
  (cd apps/api && python -m uvicorn aegis_api.main:app --host 127.0.0.1 --port 8000) &
  API_PID=$!
  (cd apps/web && npm run dev -- --host 127.0.0.1 --port 5173) &
  WEB_PID=$!
  sleep 2
  if command -v xdg-open >/dev/null 2>&1; then
    xdg-open "http://127.0.0.1:5173" >/dev/null 2>&1 || true
  elif command -v open >/dev/null 2>&1; then
    open "http://127.0.0.1:5173" >/dev/null 2>&1 || true
  fi
  ok "API http://127.0.0.1:8000  ·  UI http://127.0.0.1:5173"
  trap 'kill ${API_PID} ${WEB_PID} 2>/dev/null || true' EXIT INT TERM
  wait
}

ensure_mpi || true
ensure_python
ensure_node
write_env
start_aegis
